- .github/ISSUE_TEMPLATE/🐞bug.md
- .github/ISSUE_TEMPLATE/🛠️feature.md
> [Chore] 이슈 템플릿 title 수정

- src/docs/asciidoc/monthly-goal.adoc
- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalAddRequest.java
- src/main/java/com/sillim/recordit/goal/domain/Member.java
- src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
- src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepository.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalService.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/controller/dto/request/MonthlyAddRequestTest.java
- src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
- src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
월 목표 추가 API 구현
- Member 도메인 구현 전이므로 임시로 생성 및 사용
> [Feature] 월 목표 추가 API 구현 및 테스트

- src/docs/asciidoc/monthly-goal.adoc
- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/controller/dto/response/MonthlyGoalListResponse.java
- src/main/java/com/sillim/recordit/goal/repository/MemberJpaRepository.java
- src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepository.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
- src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
- src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
- 월 목표 목록 조회 API 구현
- 월 목표 목록 조회 API 단위 테스트
- API 문서화
> [Feature] 월 목표 목록 조회 API 구현 및 단위 테스트

- .github/workflows/codereview.yml
> chore: Create codereview.yml

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- Dockerfile
- appspec.yml
- deploy/deploy.sh
- docker-compose.yml
- src/main/resources/application-prod.yml
배포 파일 구성
Dockerfile
docker-compose.yml
deploy.sh
appspec.yml
> 🔧 chore[#60]: 배포파일 구성

- build.gradle
- src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
- src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
월별 캘린더 일정 조회 기능 구현
querydsl 의존성 추가
QuerydslSupportRepository 추가
> ✨ feature[#51]: 월별 캘린더 일정 조회 기능 구현

- build.gradle
- src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
- src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
> Release schedule merged main

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
- src/main/java/com/sillim/recordit/calendar/dto/response/CalendarResponse.java
- src/main/java/com/sillim/recordit/calendar/repository/CalendarRepository.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
- src/main/java/com/sillim/recordit/config/security/authenticate/CurrentMember.java
- src/main/java/com/sillim/recordit/member/domain/AuthorizedUser.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
캘린더 조회 기능 구현
CurrentMember annotation 추가
> ✨ feature[#66]: 캘린더 조회 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
- src/main/java/com/sillim/recordit/global/validation/common/ColorHexValid.java
- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
> ✨ feature[#68]: 캘린더 추가 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/calendar/InvalidCalendarException.java
- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
> ✨ feature[#70]: 캘린더 삭제 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
- src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/calendar/InvalidCalendarException.java
- src/main/java/com/sillim/recordit/global/validation/common/ColorHexValid.java
- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
Release calendar merge to main
> Release calendar merge to main

- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/main/java/com/sillim/recordit/schedule/dto/response/MonthScheduleResponse.java
monthscheduleresponse에 title 필드 추가
> ✨ feature[#73]: monthscheduleresponse에 title 필드 추가

- src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDuration.java
일정 시각 저장 시 0초가 아닌 현재 초가 저장되는 현상 수정
> 🚑️ hotfix[#76]: 일정 시각 저장 시 0초가 아닌 현재 초가 저장되는 현상 수정

- src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
- src/main/java/com/sillim/recordit/member/service/SignupService.java
- src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
> ✨ feature[#78]: 회원가입 시 기본 캘린더가 생성되는 기능 구현

- src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDuration.java
> 🚑️ hotfix[#76]: 시, 분은 원래대로 저장되도록 수정

- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
월별 일정 조회 시 시작일의 오름차순으로 조회되도록 수정
> ✨ feature[#81]: 월별 일정 조회 시 시작일의 오름차순으로 조회되도록 수정

- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
> Release schedule

- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
시작 날짜의 오름차순, 끝 날짜의 내림차순으로 조회되도록 구현
> ✨ feature[#81]: 시작 날짜의 오름차순, 끝 날짜의 내림차순으로 조회되도록 구현

- src/docs/asciidoc/monthly-goal.adoc
- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalRepository.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
- 월 목표 삭제 기능 구현 및 테스트
- API 문서화
- 큰 변동사항 없음
> Feature 55: 월 목표 삭제 기능 구현

- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
- src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
- src/main/java/com/sillim/recordit/schedule/domain/vo/MonthOfYear.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
> 일간 일정 조회 기능 구현

- src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
🚑️ hotfix[#96]: setLocation 필드가 null로 반환되는 현상 수정
> 🚑️ hotfix[#96]: setLocation 필드가 null로 반환되는 현상 수정

- src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
> 일별 일정 반환 필드 추가

- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/common/InvalidRequestException.java
- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
- src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
- src/main/java/com/sillim/recordit/schedule/domain/ScheduleAlarm.java
- src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
- src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/repository/ScheduleAlarmRepository.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleAlarmService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
- src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
일정 알람 1:N 관계로 추출
일정 알람 1:N 관계로 추출
> Feature 108 일정 알람 1:N 관계로 추출

- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
- src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
- src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
일정 삭제 기능 구현
단일 일정 삭제 기능
그룹 내 전체 일정 삭제 기능
그룹 내 특정 일자 이후 일정 삭제 기능
> Feature 116 일정 삭제 기능 구현

- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
- 월 목표 추가 API 호출 시 id 반환하도록 수정
> Fix 120: 월 목표 도메인 API 연동 중 발생한 수정사항 반영

- src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
DayScheduleResponse에 CalendarId 필드 추가
> ✨ feature[#128]: DayScheduleResponse에 CalendarId 필드 추가

- src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
ScheduleAlarms orphanRemoval 에러 수정
> 🚑️ hotfix[#132]: ScheduleAlarms orphanRemoval 에러 수정

- src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
> 🚑️ hotfix[#134]: scheduleGroup -> repetitionPattern cascade Persist 누락

- src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
- src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
> 🚑️ hotfix[#136]: RepetitionPattern 생성으로 인한 unique constraint 에러 수정

- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
그룹 일정에서 반복 해제 시 일정이 삭제되는 현상 수정
> 🚑️ hotfix[#138]: 그룹 일정에서 반복 해제 시 일정이 삭제되는 현상 수정

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/FeedImage.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedContent.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImageUrl.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedTitle.java
- src/main/java/com/sillim/recordit/feed/dto/request/FeedAddRequest.java
- src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/global/advice/feed/FeedControllerAdvice.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedContentException.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageCountException.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageUrlException.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedImageTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedContentTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImageUrlTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedTitleTest.java
- src/test/java/com/sillim/recordit/feed/fixture/FeedFixture.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
> Feature 140 피드 생성 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/FeedImage.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedContent.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImageUrl.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedTitle.java
- src/main/java/com/sillim/recordit/feed/dto/request/FeedAddRequest.java
- src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/global/advice/feed/FeedControllerAdvice.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedContentException.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageCountException.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageUrlException.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedImageTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedContentTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImageUrlTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedTitleTest.java
- src/test/java/com/sillim/recordit/feed/fixture/FeedFixture.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
> Release feed

- src/docs/asciidoc/task.adoc
- src/main/java/com/sillim/recordit/task/controller/TaskController.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepository.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepositoryImpl.java
- src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
- src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
- src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
- src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
- src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
- src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
- 선택한 할 일 포함, 할 일 그룹 내에 있는 해당 날짜 이후의 할 일을 수정한다.
> Feature 142: 할 일 그룹 내 이후 할 일 전체 수정 기능 구현

- build.gradle
- docker-compose.yml
- src/main/java/com/sillim/recordit/config/aws/S3Config.java
- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/dto/request/FeedAddRequest.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
- src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/common/FileGenerateException.java
- src/main/java/com/sillim/recordit/global/exception/common/FileNotFoundException.java
- src/main/java/com/sillim/recordit/global/util/FileUtils.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/test/java/com/sillim/recordit/RecorditApplicationTests.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
- src/test/java/com/sillim/recordit/feed/fixture/FeedFixture.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
- src/test/java/com/sillim/recordit/global/util/FileUtilsTest.java
- src/test/java/com/sillim/recordit/member/service/google/GoogleOidcClientTest.java
- src/test/java/com/sillim/recordit/member/service/kakao/KakaoOidcClientTest.java
- src/test/resources/application-test.yml
> Feature 145 피드 이미지 업로드 기능 구현

- docker-compose.yml
- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
- src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
- src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
- src/main/java/com/sillim/recordit/global/util/FileUtils.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
- src/test/java/com/sillim/recordit/feed/repository/FeedRepositoryTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
- src/test/java/com/sillim/recordit/global/util/FileUtilsTest.java
- src/test/resources/application-test.yml
> Feature 149 피드 상세 조회 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
- src/main/java/com/sillim/recordit/global/dto/response/SliceResponse.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
> Feature 152 피드 목록 조회 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/FeedLike.java
- src/main/java/com/sillim/recordit/feed/domain/FeedScrap.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
- src/main/java/com/sillim/recordit/feed/repository/FeedLikeRepository.java
- src/main/java/com/sillim/recordit/feed/repository/FeedScrapRepository.java
- src/main/java/com/sillim/recordit/feed/service/FeedLikeQueryService.java
- src/main/java/com/sillim/recordit/feed/service/FeedLikeService.java
- src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
- src/main/java/com/sillim/recordit/feed/service/FeedScrapQueryService.java
- src/main/java/com/sillim/recordit/feed/service/FeedScrapService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedLikeException.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedLikeQueryServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedLikeServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedScrapQueryServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedScrapServiceTest.java
> Feature 155 피드 좋아요/스크랩 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
> Feature 158 피드 삭제 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/dto/request/FeedModifyRequest.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
> Feature 159 피드 수정 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/domain/Feed.java
- src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
- src/main/java/com/sillim/recordit/feed/dto/request/FeedModifyRequest.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
- src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
> merge develop into main

- src/main/java/com/sillim/recordit/feed/controller/FeedCommentController.java
- src/main/java/com/sillim/recordit/feed/domain/FeedComment.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedCommentInListResponse.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepository.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/repository/FeedCommentRepository.java
- src/main/java/com/sillim/recordit/feed/service/FeedCommentQueryService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
- src/test/java/com/sillim/recordit/feed/controller/FeedCommentControllerTest.java
- src/test/java/com/sillim/recordit/feed/domain/FeedCommentTest.java
- src/test/java/com/sillim/recordit/feed/domain/vo/FeedCommentContentTest.java
- src/test/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepositoryTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommentCommandServiceTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommentQueryServiceTest.java
> Feature 167 피드 댓글 조회 기능 구현

- src/main/java/com/sillim/recordit/task/controller/TaskController.java
- src/main/java/com/sillim/recordit/task/domain/Task.java
- src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
- src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
- src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
- src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
- 단일 할 일의 내용만을 수정
- 단일 할 일 수정 + 반복 패턴 추가
> Feature 169: 단일 할 일 수정 기능 구현

- src/main/java/com/sillim/recordit/task/controller/TaskController.java
- src/main/java/com/sillim/recordit/task/domain/Task.java
- src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
- src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
- src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
- src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
> Feature 174: 그룹 내 할 일 전체 삭제 기능 구현

- src/main/java/com/sillim/recordit/task/controller/TaskController.java
- src/main/java/com/sillim/recordit/task/domain/Task.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepository.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepositoryImpl.java
- src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
- src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
- src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
- src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
- src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
- 선택한 할 일 포함 이후의 할일 전체 삭제
- 선택한 할 일만 삭제
> Feature 176: 선택 할 일 이후 할 일 전체 삭제 기능, 선택 할 일 단일 삭제 기능 구현

- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
- src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
- src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
- src/main/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriod.java
- src/main/java/com/sillim/recordit/goal/dto/RelatedGoals.java
- src/main/java/com/sillim/recordit/goal/dto/request/WeeklyGoalUpdateRequest.java
- src/main/java/com/sillim/recordit/goal/repository/WeeklyGoalRepository.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
- src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
- src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
- src/main/java/com/sillim/recordit/task/controller/TaskController.java
- src/main/java/com/sillim/recordit/task/domain/Task.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepository.java
- src/main/java/com/sillim/recordit/task/repository/CustomTaskRepositoryImpl.java
- src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
- src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
- src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriodTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
- src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
- src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
- src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
- src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
- src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
- src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
- 월간 목표 기능 리팩토링
- 주간 목표 추가 기능 구현 및 테스트
> Feature 178: 주간 목표 추가 기능 구현

- .github/workflows/ci.yml
- src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
- src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
- src/main/java/com/sillim/recordit/goal/dto/response/RelatedMonthlyGoalResponse.java
- src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalDetailsResponse.java
- src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalResponse.java
- src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepository.java
- src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepositoryImpl.java
- src/main/java/com/sillim/recordit/goal/service/WeeklyGoalQueryService.java
- src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/domain/MonthlyGoalTest.java
- src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
- src/test/java/com/sillim/recordit/goal/repository/WeeklyGoalRepositoryTest.java
- src/test/java/com/sillim/recordit/goal/service/WeeklyGoalQueryServiceTest.java
- src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
> Feature 183: 주간 목표 상세 조회 기능 구현

- src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
- src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
- src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
- src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
> Feature 185: 주간 목표 수정 기능 구현

- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
- src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
- src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/domain/MonthlyGoalTest.java
- src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
- src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
- 주간 목표 달성 상태 변경 기능 구현 및 테스트
- `MonthlyGoalController`의 URI 수정
> Feature 187: 주간 목표 달성 상태 변경 기능 구현

- src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
- src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
- src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
- src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
- src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
- src/test/java/com/sillim/recordit/goal/domain/MonthlyGoalTest.java
- src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
- src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
> Feature 189: 주간 목표 삭제 기능 구현

- src/main/java/com/sillim/recordit/feed/controller/FeedController.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
- src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
- src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
- src/main/java/com/sillim/recordit/member/controller/MemberController.java
- src/main/java/com/sillim/recordit/member/dto/response/ProfileResponse.java
- src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
- src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
- src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
- src/test/java/com/sillim/recordit/member/controller/MemberControllerTest.java
> Feature 193 프로필 조회 기능 구현

- src/main/java/com/sillim/recordit/member/controller/MemberController.java
- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/main/java/com/sillim/recordit/member/dto/request/ProfileModifyRequest.java
- src/main/java/com/sillim/recordit/member/service/MemberCommandService.java
- src/test/java/com/sillim/recordit/member/controller/MemberControllerTest.java
- src/test/java/com/sillim/recordit/member/service/MemberCommandServiceTest.java
프로필 정보 수정 기능 구현
MemberCommandService 정의
> feature[#201]: 프로필 정보 수정 기능 구현

- build.gradle
- src/main/java/com/sillim/recordit/config/gcp/FirebaseConfig.java
- src/main/java/com/sillim/recordit/pushalarm/service/PushAlarmService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleAlarmJob.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/test/java/com/sillim/recordit/pushalarm/service/PushAlarmServiceTest.java
- src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
푸시 알람 전송 시 페이로드 데이터가 포함되도록 수정
PushAlarmService에 페이로드 argument 추가
> Feature 211 푸시 알람 전송 시 페이로드 데이터가 포함되도록 수정

- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/main/java/com/sillim/recordit/member/domain/MemberDevice.java
- src/main/java/com/sillim/recordit/member/dto/request/LoginRequest.java
- src/main/java/com/sillim/recordit/member/dto/request/MemberInfo.java
- src/main/java/com/sillim/recordit/member/repository/CustomMemberDeviceRepository.java
- src/main/java/com/sillim/recordit/member/repository/CustomMemberDeviceRepositoryImpl.java
- src/main/java/com/sillim/recordit/member/repository/MemberDeviceRepository.java
- src/main/java/com/sillim/recordit/member/service/AuthenticationService.java
- src/main/java/com/sillim/recordit/member/service/LoginService.java
- src/main/java/com/sillim/recordit/member/service/MemberDeviceService.java
- src/main/java/com/sillim/recordit/member/service/google/GoogleAuthenticationService.java
- src/main/java/com/sillim/recordit/member/service/kakao/KakaoAuthenticationService.java
- src/main/java/com/sillim/recordit/member/service/naver/NaverAuthenticationService.java
- src/main/java/com/sillim/recordit/pushalarm/service/PushAlarmService.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleAlarmJob.java
- src/test/java/com/sillim/recordit/config/security/filter/JwtAuthenticationFilterTest.java
- src/test/java/com/sillim/recordit/member/controller/LoginControllerTest.java
- src/test/java/com/sillim/recordit/member/service/LoginServiceTest.java
- src/test/java/com/sillim/recordit/member/service/MemberDeviceServiceTest.java
- src/test/java/com/sillim/recordit/member/service/NaverAuthenticationServiceTest.java
- src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
- src/test/java/com/sillim/recordit/member/service/google/GoogleAuthenticationServiceTest.java
- src/test/java/com/sillim/recordit/member/service/kakao/KakaoAuthenticationServiceTest.java
- src/test/java/com/sillim/recordit/pushalarm/service/PushAlarmServiceTest.java
로그인한 여러 디바이스에서 FCM 토큰을 받을 수 있도록 수정
MemberDevice Entity 추가
MemberDeviceService class 추가
MemberDeviceRepository, CustomMemberDeviceRepository, CustomMemberDeviceRepositoryImpl 추가
ScheduleAlarmJob에서 pushAlarmToken을 String -> List<String> 으로 변환
> Feature 218 로그인한 여러 디바이스에서 FCM 토큰을 받을 수 있도록 수정

- src/main/java/com/sillim/recordit/feed/dto/response/FeedCommentInListResponse.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
- src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/main/java/com/sillim/recordit/member/dto/request/MemberInfo.java
- src/main/java/com/sillim/recordit/member/dto/response/ProfileResponse.java
- src/main/java/com/sillim/recordit/member/service/google/GoogleAuthenticationService.java
- src/main/java/com/sillim/recordit/member/service/kakao/KakaoAuthenticationService.java
- src/main/java/com/sillim/recordit/member/service/naver/NaverAuthenticationService.java
- src/test/java/com/sillim/recordit/config/security/filter/JwtAuthenticationFilterTest.java
- src/test/java/com/sillim/recordit/member/fixture/MemberFixture.java
- src/test/java/com/sillim/recordit/member/service/LoginServiceTest.java
- src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
- src/test/java/com/sillim/recordit/pushalarm/service/PushAlarmServiceTest.java
멤버 프로필 사진 필드 추가
Member class에 profileImageUrl 필드 추가
FeedInListResponse, FeedDetailsResponse FeedCommentInListResponse에 memberProfileImageUrl 필드 추가
> Feature 220 멤버 프로필 사진 필드 추가

- src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
- src/main/java/com/sillim/recordit/gcp/service/ImageUploadService.java
- src/main/java/com/sillim/recordit/member/controller/MemberController.java
- src/main/java/com/sillim/recordit/member/domain/Member.java
- src/main/java/com/sillim/recordit/member/service/MemberCommandService.java
- src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
- src/test/java/com/sillim/recordit/gcp/service/ImageUploadServiceTest.java
프로필 이미지 수정 기능 구현
FeedImageUploadService -> ImageUploadService로 변경
profileImageUrl 수정 메서드 추가
> Feature 223 프로필 이미지 수정 기능 구현

- build.gradle
- src/main/java/com/sillim/recordit/config/security/SecurityConfig.java
- src/main/java/com/sillim/recordit/config/security/jwt/JwtProvider.java
- src/main/java/com/sillim/recordit/config/security/oauth2/DefaultUserService.java
- src/main/java/com/sillim/recordit/config/security/oauth2/LoginMember.java
- src/main/java/com/sillim/recordit/config/security/oauth2/OAuth2Request.java
- src/main/java/com/sillim/recordit/config/security/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/AttributeMapper.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/AttributeMapperFactory.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/GoogleAttributeMapper.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/KakaoAttributeMapper.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/LoginMemberMapper.java
- src/main/java/com/sillim/recordit/config/security/oauth2/mapper/NaverAttributeMapper.java
- src/main/java/com/sillim/recordit/member/controller/LoginController.java
- src/main/java/com/sillim/recordit/member/dto/request/WebLoginRequest.java
- src/main/java/com/sillim/recordit/member/service/LoginService.java
- src/main/java/com/sillim/recordit/member/service/MemberQueryService.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/test/resources/application-test.yml
OAuth2 로그인 기능 구현
OAuth2 로그인 관련 클래스 추가
SecurityConfig에서 cors 설정 추가
LoginController에 webLogin 메서드 추가
> Feature 226 OAuth2 로그인 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
캘린더 주인이 아니여도 멤버 목록이 보이도록 수정
캘린더 소유 검증 코드 삭제
> Feature 230 캘린더 주인이 아니여도 멤버 목록이 보이도록 수정

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
- src/main/java/com/sillim/recordit/calendar/dto/request/CalendarModifyRequest.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
캘린더 수정 기능 구현
CalendarController, CalendarService에 캘린더 수정 메서드 작성
> Feature 232 캘린더 수정 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/repository/CalendarMemberRepository.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
캘린더 멤버 삭제 기능 구현
CalendarMemberController, CalendarMemberService에 캘린더 멤버 삭제 메서드 추가
> Feature 237 캘린더 멤버 삭제 기능 구현

- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
> hotfix[#242]: ClassMember가 중복 저장되는 문제 해결

- src/main/java/com/sillim/recordit/calendar/controller/CalendarCategoryController.java
- src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
- src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
- src/main/java/com/sillim/recordit/calendar/domain/CalendarCategory.java
- src/main/java/com/sillim/recordit/calendar/domain/CalendarMember.java
- src/main/java/com/sillim/recordit/calendar/repository/CalendarCategoryRepository.java
- src/main/java/com/sillim/recordit/calendar/repository/CalendarMemberRepository.java
- src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImpl.java
- src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepositoryImpl.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryService.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
- src/main/java/com/sillim/recordit/calendar/service/JoinCalendarService.java
- src/main/java/com/sillim/recordit/category/domain/ScheduleCategory.java
- src/main/java/com/sillim/recordit/category/repository/ScheduleCategoryRepository.java
- src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
- src/main/java/com/sillim/recordit/category/service/ScheduleCategoryQueryService.java
- src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
- src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
- src/test/java/com/sillim/recordit/calendar/domain/CalendarMemberTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryServiceTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
- src/test/java/com/sillim/recordit/calendar/service/JoinCalendarServiceTest.java
- src/test/java/com/sillim/recordit/category/service/ScheduleCategoryQueryServiceTest.java
> Feature 251 캘린더, 카테고리 soft delete 적용

- src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
- src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
- src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
> feature[#253]: 일정 검색 기능 구현

- src/main/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriod.java
- src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepositoryImpl.java
- src/test/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriodTest.java
- src/test/java/com/sillim/recordit/goal/repository/WeeklyGoalRepositoryTest.java
> fix[#255]: 주 목표 조회 시 주차에 맞게 조회되도록 수정

- src/main/java/com/sillim/recordit/calendar/controller/CalendarCategoryController.java
- src/main/java/com/sillim/recordit/calendar/repository/CalendarCategoryRepository.java
- src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepository.java
- src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepositoryImpl.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryCommandService.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryQueryService.java
- src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
- src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
- src/main/java/com/sillim/recordit/member/service/SignupService.java
- src/test/java/com/sillim/recordit/calendar/controller/CalendarCategoryControllerTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryCommandServiceTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryQueryServiceTest.java
- src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
- src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
> fix[#266]: 카테고리가 제대로 삭제되지 않는 현상 수정

- src/main/java/com/sillim/recordit/task/dto/response/TaskDetailsResponse.java
- src/main/resources/application-prod.yml
> chore[#275]: dialect 지정

- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
서버 스펙에 따른 Tomcat 설정 조정
local 및 production에 톰켓 설정 추가
> chore: 서버 스펙에 따른 Tomcat 설정 조정

- src/main/resources/application-prod.yml
> chore[#302]: prod neo4j env 추가

- src/main/java/com/sillim/recordit/feed/service/FeedLikeService.java
- src/main/java/com/sillim/recordit/pushalarm/dto/AlarmType.java
- src/main/java/com/sillim/recordit/pushalarm/dto/PushMessage.java
- src/test/java/com/sillim/recordit/feed/service/FeedLikeServiceTest.java
> feature[#332]: 좋아요 알림 기능 구현
